name: Pipeline-HML

on:
  push:
    branches: [ "stage" ]

jobs:
   Integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c Release -o ./publish

   Deploy:
    runs-on: ubuntu-latest
    needs: Integration

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish -c Release -o ./publish
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './publish/wwwroot/appsettings.Production.json'
      env:
          ApiGateway.BaseUrl: ${{ secrets.BASE_URL_HML }}
    - name: Deploy
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      run: aws s3 sync ./publish/wwwroot s3://${{ secrets.BUCKET_NAME_HML }} --delete